export interface User {
  username: string;
  // Note: In a real app, never store passwords directly.
  // This is a simplified model for local credential simulation.
}

export interface BankAccount {
  id: string; // unique id, e.g., generated by uuid or timestamp
  userId: string; // To associate account with a user
  accountName: string;
  bankName: string;
  balance: number;
  accountType: AccountType; // e.g., Checking, Savings
  description?: string;
  category?: string; // AI categorized
  categoryConfidence?: number;
  // icon could be a string path or an imported component/SVG
  // For simplicity, we might use a generic icon based on type or bankName initially
}

export enum AccountType {
  CHECKING = "Checking",
  SAVINGS = "Savings",
  CREDIT_CARD = "Credit Card",
  INVESTMENT = "Investment",
  LOAN = "Loan",
  MORTGAGE = "Mortgage",
  OTHER = "Other",
}

export interface UserSettings {
  theme?: "light" | "dark" | "system";
  emailNotifications?: boolean;
  pushNotifications?: boolean;
  shareData?: boolean;
}
